language: java
jdk:
- oraclejdk8

deploy:
  provider: releases
  api_key:
    secure: UQ5FJAMEbj535LX+dWJQtBZZrtJefSmb8xkgthRAqveieyfhGAubwn27v2I0WqJUYWOIv5CyJmzMEyNnxy+ZUEFLBe81Wl45qqlCIMH2f1kYPqbG3V12uSHNOZJI4UIrSvNmEQqBrBW7QZzRaOrA+7lUWIK0vaj8QXIvsvwJe5EIGfHUPoPVFyO0RSJbqGfXAN5CZzfKmdTVdjU3LO85chX7vtknT4YmVTtmf6gotF1infENtkRomr7uFeNpLzTyHG7GGXPg0HYyORkV2AcucbOxIDBJwXe6+EdUPhLXLAsQDd+yNueYrXSwT4VHi12jMXhvqfb8E3dTbTFlFIEqvD/sq0belHz5sMOKMXeOR1XYRMo1KL8sCJuFB6pIXjzmZGhD7zsVC1RCD36F4B588G7zsP4k+nfT6FaQ/e06yxB6LFQTUzTvmRfzPRepxX9UryTE6/FH18SK5uyJMFyiefnKWE6fFODW3QOQeed2uKfJDePt9aDtV3dW/TZ1EAcXnAe2XHMk6Ug0kfv75AvnD1mWH/R7YzGaVyQDnEfMuSBJdb7kfuE3nMqLYvaUMAAdMh8gLnce/unqHygvca35lqt+h4WvEO+Bxm90M3WN+Yk1sV1NEBNgfLgwATjj34u1JvASuuXvA9bAnWHtGXlIXULsGIfqPv53hDM60m8fLgc=
  file: "./build/libs/SuperTTTApi.jar"
  skip_cleanup: true
  on:
    tags: true
